export * from './patient-information/patient-information'
export * from './viewphotos/viewphotos'
export * from './login/login'
export * from './patient-photos/patient-photos'
export * from './thankyou/thankyou'